-- do migration file

DROP TYPE IF EXISTS category_options;

CREATE TYPE category_options AS ENUM(
    'Breakfast',
    'Lunch',
    'Dinner'
);

CREATE TABLE menu_tb (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    image_url TEXT,
    calories INTEGER,
    carbs INTEGER,
    protein INTEGER,
    fat INTEGER,
    category category_options NOT NULL
);




